### ISSUE TITLE
Cli args not correctly parsed on windows

### ISSUE THREAD

**Issue by relu91** [vcharpenay/STTL.js#18]
I've just used the cli under windows and I noticed that the `cli.js` tries to look for arguments on the command line but it fails to detect them. Basically, it just prints the help message. 

Here's the args object under windows (MINGW):
```
[
  'C:\\Program Files\\nodejs\\node.exe',
  'C:\\Users\\reluc\\Progetti\\wot-thing-description\\node_modules\\sttl\\src\\cli.js',
  '-i',
  'validation/td-validation.ttl',
  'context/td-context.ttl',
  'ontology/td.ttl',
  'ontology/hctl.ttl',
  'ontology/jsonschema.ttl',
  'ontology/wotsec.ttl',
  '-t',
  'templates.sparql',
  '-c',
  'http://w3c.github.io/wot-thing-description/#main',
  '-o',
  'index.html'
]
``` 

I think the problem is that cli.js tries to search for `/node` but on windows is `\node.exe`:
https://github.com/vcharpenay/STTL.js/blob/9f11c1a8090ae816883ac206713e29d47540d0af/src/cli.js#L24-L25

**Comment by vcharpenay** [comment]
see changes in branch [`fix-cli-windows`](https://github.com/vcharpenay/STTL.js/tree/fix-cli-windows): can you now execute the CLI?

**Comment by relu91** [comment]
yes, fixed! thanks and sorry for the late response.
