### ISSUE TITLE
STTL does not run correctly on Windows 10

### ISSUE THREAD

**Issue by FadySalama** [vcharpenay/STTL.js#19]
When I run STTL using either Git Bash or Cygwin on Windows (mainly when rendering W3C Thing Description spec), the STTL doesn't recognize the arguments. The issue is mainly caused  by this line https://github.com/vcharpenay/STTL.js/blob/9f11c1a8090ae816883ac206713e29d47540d0af/src/cli.js#L24
because in Windows, the path ends with (\\node.exe).

**Comment by relu91** [comment]
@vcharpenay already solved this in #18, however, I belive he forgot to merge the changes back to the main branch. Meanwhile, you can try with https://github.com/vcharpenay/STTL.js/tree/fix-cli-windows branch (`npm i  git+https://github.com/vcharpenay/STTL.js.git#fix-cli-windows`)

**Comment by vcharpenay** [comment]
I've just merged it, thanks for the reminder.
